name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "test-release"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PROJECT_NAME: NicerAuras
    steps:
      - uses: actions/checkout@v2
      - name: Setup Build Environment
        run: |
          build_version() {
            local GAME_VERSION=$1
            local INTERFACE_VERSION=$2
            local ACE3_URL=$3
            local GIT_TAG=$(git describe --exact-match --tags)

            mkdir -p $PROJECT_NAME/Libs
            curl -L -o ace3.zip "$ACE3_URL"
            unzip ace3.zip -d temp/
            local ACE3_LIBS=(
              "LibStub"
              "CallbackHandler-1.0"
              "AceAddon-3.0"
              "AceGUI-3.0"
              "AceConfig-3.0"
              "AceEvent-3.0"
              "AceConsole-3.0"
              "AceDB-3.0"
              "AceTimer-3.0"
              "AceDBOptions-3.0"
            )
            for lib in "${ACE3_LIBS[@]}"; do
              cp -r temp/Ace3/$lib $PROJECT_NAME/Libs/
            done

            sed -i "s/^## Interface: [0-9]\+/## Interface: $INTERFACE_VERSION/" "$PROJECT_NAME/$PROJECT_NAME.toc"
            sed -i "s/^## Version: [0-9.]\+/## Version: $GIT_TAG/" "$PROJECT_NAME/$PROJECT_NAME.toc"

            zip -r ${PROJECT_NAME}_${GAME_VERSION}.zip $PROJECT_NAME
            echo "${PROJECT_NAME}_${GAME_VERSION}"
          }

          build_version "WOTLK" "30402" \
            "https://www.wowace.com/projects/ace3/files/440275/download"

          build_version "TBC" "25403" \
            "https://www.wowace.com/projects/ace3/files/262066/download"


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            NicerAuras_WOTLK.zip
            NicerAuras_TBC.zip
          draft: ${{ !startsWith(github.ref, 'refs/tags/') }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && 'Release' || 'Test Release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
